export const charData = [
  {
    id: 1,
    parentId: null,
    examId: 1,
    title: 'مهندسی و صنعت',
    description: 'مهارت حل مسائل پیچیده، مهارت یادگیری پویا، مهارت مستند سازی',
    maxValue: 875,
    calcValue: 425,
    percent: 48.57,
  },
  {
    id: 2,
    parentId: null,
    examId: 1,
    title: 'فن‌آوری و علوم رایانه ای',
    description: 'مهارت معماری اطلاعات، مهارت هوش دیجیتال، مهارت تحلیل داده ها',
    maxValue: 750,
    calcValue: 375,
    percent: 50,
  },
  {
    id: 3,
    parentId: null,
    examId: 1,
    title: 'علم و پژوهش',
    description:
      'مهارت یادگیری پویا، مهارت پژوهش و جستجو، مهارت تسلط به زبان بین المللی ',
    maxValue: 650,
    calcValue: 100,
    percent: 15.38,
  },
  {
    id: 4,
    parentId: null,
    examId: 1,
    title: 'تجارت و بازرگانی',
    description:
      'مهارت مدیریت هوش هیجانی، مهارت خلاقیت و نوآوری، مهارت تسلط بر هوش دیجیتال',
    maxValue: 950,
    calcValue: 575,
    percent: 60.52,
  },
  {
    id: 5,
    parentId: null,
    examId: 1,
    title: 'هنرهای رایانه‌ای',
    description:
      'مهارت برقراری ارتباط نوشتار و زبانی، مهارت طراحی خلاقانه، سواد رسانه ای',
    maxValue: 500,
    calcValue: 175,
    percent: 35,
  },
  {
    id: 6,
    parentId: null,
    examId: 1,
    title: 'هنر',
    description:
      'مهارت ارائه خلاقانه احساسات، مهارت هنر دیجیتال، مهارت نقد پذیری',
    maxValue: 875,
    calcValue: 300,
    percent: 34.28,
  },
  {
    id: 7,
    parentId: null,
    examId: 1,
    title: 'حقوق',
    description:
      'مهارت پژوهش و جستجو، مهارت تفکر نقادانه، مهارت تجزیه و تحلیل و نتیجه گیری',
    maxValue: 550,
    calcValue: 100,
    percent: 18.18,
  },
  {
    id: 8,
    parentId: null,
    examId: 1,
    title: 'خدمات عمومی',
    description:
      'مسئولیت پذیرای اجتماعی، مهارت تصمیم گیری در شرایط بحرانی، مهارت های عمومی روانشناختی ',
    maxValue: 725,
    calcValue: 250,
    percent: 34.48,
  },
  {
    id: 9,
    parentId: null,
    examId: 1,
    title: 'پزشکی و سلامت',
    description:
      'مهارت مدیریت هیجانات، مهارت تسلط بر  شیوه نامه های  بهداشتی، مهارت همدلی کردن',
    maxValue: 625,
    calcValue: 225,
    percent: 36,
  },
  {
    id: 10,
    parentId: null,
    examId: 1,
    title: 'علوم تغذیه و آشپزی',
    description:
      'مهارت توجه به جزئیات، مهارت ترکیب و نوآوری، سواد سلامت و تندرستی',
    maxValue: 400,
    calcValue: 300,
    percent: 75,
  },
  {
    id: 11,
    parentId: null,
    examId: 1,
    title: 'آموزش',
    description:
      'مهارت ساختن طرحواره های یادگیری، مهارت و تسلط به زبان بین المللی، مهارت کلامی و اشاره',
    maxValue: 525,
    calcValue: 225,
    percent: 42.85,
  },
  {
    id: 12,
    parentId: null,
    examId: 1,
    title: 'علوم اجتماعی',
    description:
      'مهارت تحلیل رفتارهای انسانی، مهارت برقراری ارتباط موثر، مهارت پژوهش و جستجو',
    maxValue: 825,
    calcValue: 375,
    percent: 45.45,
  },
  {
    id: 13,
    parentId: null,
    examId: 1,
    title: 'ارتباطات و روابط عمومی',
    description:
      'سواد رسانه ای،\r\nمهارت مدیریت ارتباطات چندگانه،\r\nمهارت نویسندگی خلاق\r\n',
    maxValue: 525,
    calcValue: 175,
    percent: 33.33,
  },
  {
    id: 14,
    parentId: null,
    examId: 1,
    title: 'خدمات فنی و حرفه‌ای',
    description:
      'مهارت کاربری ابزار، مهارت بهداشت ایمنی و محیط زیست، مهارت تعمیر و نگهداری',
    maxValue: 525,
    calcValue: 325,
    percent: 61.9,
  },
  {
    id: 15,
    parentId: null,
    examId: 1,
    title: 'امور مالی و اقتصادی',
    description:
      'مهارت کار با اعداد و تحلیل ریاضی، مهارت ارزیابی و تخمین دقیق، مهارت برآورد اقتصادی بهینه',
    maxValue: 300,
    calcValue: 225,
    percent: 75,
  },
]
